# Generated by Django 5.1.2 on 2025-01-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_guest_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
